// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 18/01/2026, 11:51:43 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/sanid/OneDrive/Desktop/sam/solace-agent-mesh-hackathon-quickstart/frontend/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sanid/OneDrive/Desktop/sam/solace-agent-mesh-hackathon-quickstart/frontend/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sanid/OneDrive/Desktop/sam/solace-agent-mesh-hackathon-quickstart/frontend/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sanid/OneDrive/Desktop/sam/solace-agent-mesh-hackathon-quickstart/frontend/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sanid/OneDrive/Desktop/sam/solace-agent-mesh-hackathon-quickstart/frontend/app/plugins/**/*.{js,ts,mjs}","C:/Users/sanid/OneDrive/Desktop/sam/solace-agent-mesh-hackathon-quickstart/frontend/app/composables/**/*.{js,ts,mjs}","C:/Users/sanid/OneDrive/Desktop/sam/solace-agent-mesh-hackathon-quickstart/frontend/app/utils/**/*.{js,ts,mjs}","C:/Users/sanid/OneDrive/Desktop/sam/solace-agent-mesh-hackathon-quickstart/frontend/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sanid/OneDrive/Desktop/sam/solace-agent-mesh-hackathon-quickstart/frontend/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sanid/OneDrive/Desktop/sam/solace-agent-mesh-hackathon-quickstart/frontend/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sanid/OneDrive/Desktop/sam/solace-agent-mesh-hackathon-quickstart/frontend/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;